更新 i18n 中 ZH_TW 翻譯
LiteLDev/Website pull request #13
Opened 2022-09-03 07:49 UTC by vincentwang0905

> 新增 i18n 檔案中的 ZH_TW 翻譯
> 更改 zh 為 zh-CH 並新增 zh-TW

2022-09-04 03:25 UTC, Jasonzyt requested changes

2022-09-04 03:25 UTC, Jasonzyt commented on assets/js/i18n.js
> +            "firstBenefit": "完全開放的類與函數",
这里是不是搞混了

2022-09-04 06:26 UTC, vincentwang0905 commented
哈哈改錯了

2022-09-05 00:08 UTC, Jasonzyt approved these changes

2022-09-05 00:10 UTC, Jasonzyt commented
感谢贡献！

2022-09-05 00:15 UTC, merged